baseURL = "https://grass-stem.com"
disableLanguages = []
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Grass STEM | Free Premium Classes"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Grass Stem, Proudly Managed by&nbsp"
manageText = "ISODME.com"
manageLink = "https://www.isodme.com"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "course"
name = "Courses/Camps"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = ""
author = "Jonathan Lei"
contact_form_action = "https://formspree.io/xvowvyke"
description = "Grass STEM provides premium STEM classes for free. "
email = "grass4stem@gmail.com"
google_analitycs_id = "UA-173146738-1"
logo = "images/logo.png"
mobile = "Need2Delete"
top_header = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://docs.google.com/forms/d/e/1FAIpQLSeGSUgrQdmBsxu7ye4atxcbvuHe4QCkWGlCy40UxpkAkJA0jQ/viewform"
mailchimp_form_name = ""
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/Grass-STEM-105652047901110"
title = "facebook"
[[params.social]]
icon = "ti-github"
link = "https://github.com/jonathan-lei/website-teaching"
title = "github"
